import { z } from 'zod';

// ---------------------------------------------------------------------------
// Factual Metrics Schema
// Extracted deterministically — no AI involved
// ---------------------------------------------------------------------------

export const PageMetricsSchema = z.object({
  url: z.string().url(),
  wordCount: z.number().int().nonnegative(),
  h1Count: z.number().int().nonnegative(),
  h2Count: z.number().int().nonnegative(),
  h3Count: z.number().int().nonnegative(),
  ctaCount: z.number().int().nonnegative(),
  internalLinks: z.number().int().nonnegative(),
  externalLinks: z.number().int().nonnegative(),
  imageCount: z.number().int().nonnegative(),
  /** Percentage (0–100) of images that have a non-empty alt attribute */
  altTextPercent: z.number().min(0).max(100),
  metaTitle: z.string().nullable(),
  metaDescription: z.string().nullable(),
  // ---------------------------------------------------------------------------
  // Google PageSpeed Insights / Lighthouse scores (0–100, nullable)
  // null when the API is unavailable, times out, or key is not configured.
  // Audits always succeed regardless of PageSpeed availability.
  // ---------------------------------------------------------------------------
  /** Lighthouse Performance score (0–100) */
  performanceScore: z.number().int().min(0).max(100).nullable(),
  /** Lighthouse Accessibility score (0–100) */
  accessibilityScore: z.number().int().min(0).max(100).nullable(),
  /** Lighthouse Best Practices score (0–100) */
  bestPracticesScore: z.number().int().min(0).max(100).nullable(),
  /** Lighthouse SEO score (0–100) — technical audit, distinct from AI SEO insights */
  seoScore: z.number().int().min(0).max(100).nullable(),
});

export type PageMetrics = z.infer<typeof PageMetricsSchema>;

// ---------------------------------------------------------------------------
// AI Insights Schema
// Generated by OpenAI — every finding must reference metric values
// ---------------------------------------------------------------------------

const InsightCategorySchema = z.object({
  summary: z.string().min(1),
  findings: z.array(z.string().min(1)),
});

export const RecommendationSchema = z.object({
  /** 1 = highest impact, 5 = lowest */
  priority: z.number().int().min(1).max(5),
  title: z.string().min(1),
  /** Must reference at least one specific metric value */
  reasoning: z.string().min(1),
  /** Keys from PageMetrics that this recommendation is grounded in */
  metricRefs: z.array(z.string()).min(1),
});

export const AuditInsightsSchema = z.object({
  seo: InsightCategorySchema,
  messaging: InsightCategorySchema,
  cta: InsightCategorySchema,
  contentDepth: InsightCategorySchema,
  ux: InsightCategorySchema,
  recommendations: z.array(RecommendationSchema).min(3).max(5),
});

export type AuditInsights = z.infer<typeof AuditInsightsSchema>;
export type Recommendation = z.infer<typeof RecommendationSchema>;

// ---------------------------------------------------------------------------
// Combined Audit Result
// Full response returned by POST /api/audit
// ---------------------------------------------------------------------------

export const AuditResultSchema = z.object({
  metrics: PageMetricsSchema,
  insights: AuditInsightsSchema,
  auditedAt: z.string().datetime(),
});

export type AuditResult = z.infer<typeof AuditResultSchema>;
