import type { AuditInsights } from '@/types/audit';

const CATEGORIES: {
  key: keyof Omit<AuditInsights, 'recommendations'>;
  label: string;
  icon: string;
}[] = [
  { key: 'seo', label: 'SEO Structure', icon: '🔍' },
  { key: 'messaging', label: 'Messaging Clarity', icon: '💬' },
  { key: 'cta', label: 'CTA Usage', icon: '🎯' },
  { key: 'contentDepth', label: 'Content Depth', icon: '📄' },
  { key: 'ux', label: 'UX & Structure', icon: '🖥️' },
];

interface InsightCategoryCardProps {
  label: string;
  icon: string;
  summary: string;
  findings: string[];
}

function InsightCategoryCard({
  label,
  icon,
  summary,
  findings,
}: InsightCategoryCardProps) {
  return (
    <div className="rounded-lg border border-violet-100 bg-white p-5 shadow-sm">
      <div className="mb-2 flex items-center gap-2">
        <span aria-hidden="true">{icon}</span>
        <h3 className="font-semibold text-gray-900">{label}</h3>
      </div>
      <p className="mb-3 text-sm text-gray-600">{summary}</p>
      {findings.length > 0 && (
        <ul className="space-y-1.5">
          {findings.map((finding, i) => (
            <li key={i} className="flex gap-2 text-sm text-gray-700">
              <span className="mt-0.5 shrink-0 text-violet-400">•</span>
              <span>{finding}</span>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}

interface InsightsPanelProps {
  insights: AuditInsights;
}

export function InsightsPanel({ insights }: InsightsPanelProps) {
  return (
    <section aria-labelledby="insights-heading">
      <div className="mb-4 flex items-start justify-between gap-4">
        <div>
          <h2 id="insights-heading" className="text-lg font-bold text-gray-900">
            AI Analysis
          </h2>
          <p className="text-sm text-violet-600">
            Generated by Gemini — grounded in extracted metrics
          </p>
        </div>
        <span className="shrink-0 rounded-full bg-violet-100 px-3 py-1 text-xs font-medium text-violet-700">
          AI‑generated
        </span>
      </div>

      <div className="grid gap-4 sm:grid-cols-2">
        {CATEGORIES.map(({ key, label, icon }) => (
          <InsightCategoryCard
            key={key}
            label={label}
            icon={icon}
            summary={insights[key].summary}
            findings={insights[key].findings}
          />
        ))}
      </div>
    </section>
  );
}
