import type { AuditInsights } from '@/types/audit';

// ---------------------------------------------------------------------------
// Per-category visual config
// ---------------------------------------------------------------------------

const CATEGORIES: {
  key: keyof Omit<AuditInsights, 'recommendations'>;
  label: string;
  topColor: string;
  iconColor: string;
  Icon: () => React.JSX.Element;
}[] = [
  {
    key: 'seo',
    label: 'SEO Structure',
    topColor: '#3B5BDB',
    iconColor: '#3B5BDB',
    Icon: IconSearch,
  },
  {
    key: 'messaging',
    label: 'Messaging Clarity',
    topColor: '#0D9488',
    iconColor: '#0D9488',
    Icon: IconChat,
  },
  {
    key: 'cta',
    label: 'CTA Usage',
    topColor: '#EA580C',
    iconColor: '#EA580C',
    Icon: IconTarget,
  },
  {
    key: 'contentDepth',
    label: 'Content Depth',
    topColor: '#7C3AED',
    iconColor: '#7C3AED',
    Icon: IconLayers,
  },
  {
    key: 'ux',
    label: 'UX & Structure',
    topColor: '#0891B2',
    iconColor: '#0891B2',
    Icon: IconDiamond,
  },
];

// ---------------------------------------------------------------------------
// InsightCategoryCard
// ---------------------------------------------------------------------------

interface InsightCategoryCardProps {
  label: string;
  topColor: string;
  iconColor: string;
  Icon: () => React.JSX.Element;
  summary: string;
  findings: string[];
}

function InsightCategoryCard({
  label,
  topColor,
  iconColor,
  Icon,
  summary,
  findings,
}: InsightCategoryCardProps) {
  return (
    <div
      className="rounded-xl p-5"
      style={{
        backgroundColor: '#fff',
        border: '1px solid #E5E7EB',
        borderTop: `3px solid ${topColor}`,
      }}
    >
      <div className="flex items-center gap-2 mb-2">
        <span style={{ color: iconColor }}>
          <Icon />
        </span>
        <h3 className="font-semibold text-sm" style={{ color: '#111827' }}>
          {label}
        </h3>
      </div>
      <p className="text-sm mb-3 leading-relaxed" style={{ color: '#6B7280' }}>
        {summary}
      </p>
      {findings.length > 0 && (
        <ul className="space-y-1.5">
          {findings.map((finding, i) => (
            <li key={i} className="flex gap-2 text-sm" style={{ color: '#374151' }}>
              <span className="mt-1 shrink-0 w-1.5 h-1.5 rounded-full" style={{ backgroundColor: topColor, marginTop: '6px' }} />
              <span>{finding}</span>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// InsightsPanel
// ---------------------------------------------------------------------------

interface InsightsPanelProps {
  insights: AuditInsights;
}

export function InsightsPanel({ insights }: InsightsPanelProps) {
  return (
    <section aria-labelledby="insights-heading">
      {/* Section heading */}
      <div className="flex items-start justify-between gap-4 mb-5">
        <div className="flex items-start gap-3">
          <div
            className="shrink-0 w-1 self-stretch rounded-full mt-0.5"
            style={{
              background: 'linear-gradient(to bottom, #3B5BDB, #7C3AED)',
            }}
            aria-hidden="true"
          />
          <div>
            <h2 id="insights-heading" className="text-lg font-bold" style={{ color: '#111827' }}>
              AI Analysis
            </h2>
            <p className="text-sm" style={{ color: '#3B5BDB' }}>
              Generated by Gemini — grounded in extracted metrics
            </p>
          </div>
        </div>
        <span
          className="shrink-0 text-xs font-semibold uppercase tracking-widest rounded px-2 py-1"
          style={{ color: '#6B7280', border: '1px solid #E5E7EB', backgroundColor: '#F9FAFB' }}
        >
          AI-Generated
        </span>
      </div>

      {/* 2-column grid — last item spans full width if odd */}
      <div className="grid gap-4 sm:grid-cols-2">
        {CATEGORIES.map(({ key, label, topColor, iconColor, Icon }, idx) => {
          const isLastOdd = idx === CATEGORIES.length - 1 && CATEGORIES.length % 2 !== 0;
          return (
            <div key={key} className={isLastOdd ? 'sm:col-span-2' : ''}>
              <InsightCategoryCard
                label={label}
                topColor={topColor}
                iconColor={iconColor}
                Icon={Icon}
                summary={insights[key].summary}
                findings={insights[key].findings}
              />
            </div>
          );
        })}
      </div>
    </section>
  );
}

// ---------------------------------------------------------------------------
// Inline SVG icons
// ---------------------------------------------------------------------------

function IconSearch() {
  return (
    <svg width="16" height="16" viewBox="0 0 16 16" fill="none" aria-hidden="true">
      <circle cx="7" cy="7" r="4.5" stroke="currentColor" strokeWidth="1.5" />
      <line x1="10.5" y1="10.5" x2="13.5" y2="13.5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
    </svg>
  );
}

function IconChat() {
  return (
    <svg width="16" height="16" viewBox="0 0 16 16" fill="none" aria-hidden="true">
      <path d="M2 3.5C2 2.67 2.67 2 3.5 2h9C13.33 2 14 2.67 14 3.5v6c0 .83-.67 1.5-1.5 1.5H5l-3 2.5V3.5z" stroke="currentColor" strokeWidth="1.5" strokeLinejoin="round" />
    </svg>
  );
}

function IconTarget() {
  return (
    <svg width="16" height="16" viewBox="0 0 16 16" fill="none" aria-hidden="true">
      <circle cx="8" cy="8" r="6" stroke="currentColor" strokeWidth="1.5" />
      <circle cx="8" cy="8" r="3" stroke="currentColor" strokeWidth="1.5" />
      <circle cx="8" cy="8" r="1" fill="currentColor" />
    </svg>
  );
}

function IconLayers() {
  return (
    <svg width="16" height="16" viewBox="0 0 16 16" fill="none" aria-hidden="true">
      <path d="M2 5l6-3 6 3-6 3-6-3z" stroke="currentColor" strokeWidth="1.5" strokeLinejoin="round" />
      <path d="M2 8.5l6 3 6-3" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
      <path d="M2 12l6 3 6-3" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
    </svg>
  );
}

function IconDiamond() {
  return (
    <svg width="16" height="16" viewBox="0 0 16 16" fill="none" aria-hidden="true">
      <path d="M8 2l4 4-4 8-4-8 4-4z" stroke="currentColor" strokeWidth="1.5" strokeLinejoin="round" />
      <line x1="4" y1="6" x2="12" y2="6" stroke="currentColor" strokeWidth="1.5" />
    </svg>
  );
}
